// Package interfaces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package interfaces

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RegisterRequestRole.
const (
	ADMIN    RegisterRequestRole = "ADMIN"
	MERCHANT RegisterRequestRole = "MERCHANT"
	USER     RegisterRequestRole = "USER"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expiresAt"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	UserId    string    `json:"userId"`
}

// CreateInvoiceRequest defines model for CreateInvoiceRequest.
type CreateInvoiceRequest struct {
	Amount     int64      `json:"amount"`
	Currency   *string    `json:"currency,omitempty"`
	DueDate    *time.Time `json:"dueDate,omitempty"`
	MerchantId string     `json:"merchantId"`
}

// CreatePaymentIntentRequest defines model for CreatePaymentIntentRequest.
type CreatePaymentIntentRequest struct {
	// Method WALLET, VA_DUMMY, or EWALLET_DUMMY
	Method string `json:"method"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error code
	Error string `json:"error"`

	// Message Detailed error message
	Message string `json:"message"`
}

// InvoiceListResponse defines model for InvoiceListResponse.
type InvoiceListResponse struct {
	Items []InvoiceResponse `json:"items"`
	Page  int               `json:"page"`
	Size  int               `json:"size"`
}

// InvoiceResponse defines model for InvoiceResponse.
type InvoiceResponse struct {
	Amount        int64      `json:"amount"`
	CreatedAt     time.Time  `json:"createdAt"`
	Currency      string     `json:"currency"`
	DueDate       *time.Time `json:"dueDate,omitempty"`
	Id            string     `json:"id"`
	InvoiceNumber string     `json:"invoiceNumber"`
	MerchantId    string     `json:"merchantId"`
	PaymentToken  string     `json:"paymentToken"`
	Status        string     `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ProcessRefundRequest defines model for ProcessRefundRequest.
type ProcessRefundRequest struct {
	Success bool `json:"success"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`

	// Role Optional. Defaults to MERCHANT.
	Role *RegisterRequestRole `json:"role,omitempty"`
}

// RegisterRequestRole Optional. Defaults to MERCHANT.
type RegisterRequestRole string

// RequestRefundRequest defines model for RequestRefundRequest.
type RequestRefundRequest struct {
	Amount     int64  `json:"amount"`
	InvoiceId  string `json:"invoiceId"`
	MerchantId string `json:"merchantId"`
}

// RequestTopUpRequest defines model for RequestTopUpRequest.
type RequestTopUpRequest struct {
	Amount     int64   `json:"amount"`
	MerchantId string  `json:"merchantId"`
	RequestKey *string `json:"requestKey,omitempty"`
}

// SimulatePaymentIntentRequest defines model for SimulatePaymentIntentRequest.
type SimulatePaymentIntentRequest struct {
	// Outcome SUCCESS or FAILED
	Outcome string `json:"outcome"`
}

// UpdateInvoiceRequest defines model for UpdateInvoiceRequest.
type UpdateInvoiceRequest struct {
	Amount   int64      `json:"amount"`
	Currency *string    `json:"currency,omitempty"`
	DueDate  *time.Time `json:"dueDate,omitempty"`
}

// UpdateTopUpStatusRequest defines model for UpdateTopUpStatusRequest.
type UpdateTopUpStatusRequest struct {
	Success bool `json:"success"`
}

// GetDashboardStatsParams defines parameters for GetDashboardStats.
type GetDashboardStatsParams struct {
	MerchantId *string    `form:"merchantId,omitempty" json:"merchantId,omitempty"`
	StartDate  *time.Time `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate    *time.Time `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// ListInvoicesParams defines parameters for ListInvoices.
type ListInvoicesParams struct {
	MerchantId *string `form:"merchantId,omitempty" json:"merchantId,omitempty"`
	Status     *string `form:"status,omitempty" json:"status,omitempty"`
	Page       *string `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *string `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListRefundHistoryParams defines parameters for ListRefundHistory.
type ListRefundHistoryParams struct {
	MerchantId *string `form:"merchantId,omitempty" json:"merchantId,omitempty"`
	Page       *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListTopUpHistoryParams defines parameters for ListTopUpHistory.
type ListTopUpHistoryParams struct {
	MerchantId *string `form:"merchantId,omitempty" json:"merchantId,omitempty"`
	Page       *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SimulatePaymentIntentJSONRequestBody defines body for SimulatePaymentIntent for application/json ContentType.
type SimulatePaymentIntentJSONRequestBody = SimulatePaymentIntentRequest

// ProcessRefundJSONRequestBody defines body for ProcessRefund for application/json ContentType.
type ProcessRefundJSONRequestBody = ProcessRefundRequest

// UpdateTopUpStatusJSONRequestBody defines body for UpdateTopUpStatus for application/json ContentType.
type UpdateTopUpStatusJSONRequestBody = UpdateTopUpStatusRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateInvoiceJSONRequestBody defines body for CreateInvoice for application/json ContentType.
type CreateInvoiceJSONRequestBody = CreateInvoiceRequest

// UpdateInvoiceJSONRequestBody defines body for UpdateInvoice for application/json ContentType.
type UpdateInvoiceJSONRequestBody = UpdateInvoiceRequest

// RequestRefundJSONRequestBody defines body for RequestRefund for application/json ContentType.
type RequestRefundJSONRequestBody = RequestRefundRequest

// RequestTopUpJSONRequestBody defines body for RequestTopUp for application/json ContentType.
type RequestTopUpJSONRequestBody = RequestTopUpRequest

// CreatePaymentIntentJSONRequestBody defines body for CreatePaymentIntent for application/json ContentType.
type CreatePaymentIntentJSONRequestBody = CreatePaymentIntentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Admin-only dashboard/access check
	// (GET /admin/dashboard)
	AdminDashboard(c *gin.Context)
	// Admin dashboard statistics
	// (GET /admin/dashboard/stats)
	GetDashboardStats(c *gin.Context, params GetDashboardStatsParams)
	// Admin simulate payment intent outcome
	// (POST /admin/payment-intents/{intentId}/simulate)
	SimulatePaymentIntent(c *gin.Context, intentId string)
	// Admin approve refund
	// (POST /admin/refunds/{refundId}/approve)
	ApproveRefund(c *gin.Context, refundId string)
	// Admin process refund outcome
	// (POST /admin/refunds/{refundId}/process)
	ProcessRefund(c *gin.Context, refundId string)
	// Admin reject refund
	// (POST /admin/refunds/{refundId}/reject)
	RejectRefund(c *gin.Context, refundId string)
	// Admin update top-up status
	// (POST /admin/topups/{topupId}/status)
	UpdateTopUpStatus(c *gin.Context, topupId string)
	// Login merchant account
	// (POST /auth/login)
	Login(c *gin.Context)
	// Refresh JWT token
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// Register an account
	// (POST /auth/register)
	Register(c *gin.Context)
	// Health check
	// (GET /health)
	Health(c *gin.Context)
	// List invoices
	// (GET /invoices)
	ListInvoices(c *gin.Context, params ListInvoicesParams)
	// Create invoice
	// (POST /invoices)
	CreateInvoice(c *gin.Context)
	// Delete invoice
	// (DELETE /invoices/{id})
	DeleteInvoice(c *gin.Context, id string)
	// Get invoice detail
	// (GET /invoices/{id})
	GetInvoice(c *gin.Context, id string)
	// Update invoice
	// (PUT /invoices/{id})
	UpdateInvoice(c *gin.Context, id string)
	// Merchant-only profile/access check
	// (GET /merchant/profile)
	MerchantProfile(c *gin.Context)
	// Refund history
	// (GET /merchant/refunds)
	ListRefundHistory(c *gin.Context, params ListRefundHistoryParams)
	// Merchant request refund
	// (POST /merchant/refunds)
	RequestRefund(c *gin.Context)
	// Top-up history
	// (GET /merchant/topups)
	ListTopUpHistory(c *gin.Context, params ListTopUpHistoryParams)
	// Merchant request top-up
	// (POST /merchant/topups)
	RequestTopUp(c *gin.Context)
	// Resolve public payment link
	// (GET /pay/{token})
	ResolvePaymentLink(c *gin.Context, token string)
	// Create payment intent
	// (POST /pay/{token}/intents)
	CreatePaymentIntent(c *gin.Context, token string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AdminDashboard operation middleware
func (siw *ServerInterfaceWrapper) AdminDashboard(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminDashboard(c)
}

// GetDashboardStats operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardStats(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardStatsParams

	// ------------- Optional query parameter "merchantId" -------------

	err = runtime.BindQueryParameter("form", true, false, "merchantId", c.Request.URL.Query(), &params.MerchantId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter merchantId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "startDate", c.Request.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter startDate: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "endDate", c.Request.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter endDate: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDashboardStats(c, params)
}

// SimulatePaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) SimulatePaymentIntent(c *gin.Context) {

	var err error

	// ------------- Path parameter "intentId" -------------
	var intentId string

	err = runtime.BindStyledParameterWithOptions("simple", "intentId", c.Param("intentId"), &intentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter intentId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SimulatePaymentIntent(c, intentId)
}

// ApproveRefund operation middleware
func (siw *ServerInterfaceWrapper) ApproveRefund(c *gin.Context) {

	var err error

	// ------------- Path parameter "refundId" -------------
	var refundId string

	err = runtime.BindStyledParameterWithOptions("simple", "refundId", c.Param("refundId"), &refundId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter refundId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApproveRefund(c, refundId)
}

// ProcessRefund operation middleware
func (siw *ServerInterfaceWrapper) ProcessRefund(c *gin.Context) {

	var err error

	// ------------- Path parameter "refundId" -------------
	var refundId string

	err = runtime.BindStyledParameterWithOptions("simple", "refundId", c.Param("refundId"), &refundId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter refundId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessRefund(c, refundId)
}

// RejectRefund operation middleware
func (siw *ServerInterfaceWrapper) RejectRefund(c *gin.Context) {

	var err error

	// ------------- Path parameter "refundId" -------------
	var refundId string

	err = runtime.BindStyledParameterWithOptions("simple", "refundId", c.Param("refundId"), &refundId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter refundId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RejectRefund(c, refundId)
}

// UpdateTopUpStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTopUpStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "topupId" -------------
	var topupId string

	err = runtime.BindStyledParameterWithOptions("simple", "topupId", c.Param("topupId"), &topupId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter topupId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTopUpStatus(c, topupId)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// ListInvoices operation middleware
func (siw *ServerInterfaceWrapper) ListInvoices(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInvoicesParams

	// ------------- Optional query parameter "merchantId" -------------

	err = runtime.BindQueryParameter("form", true, false, "merchantId", c.Request.URL.Query(), &params.MerchantId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter merchantId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInvoices(c, params)
}

// CreateInvoice operation middleware
func (siw *ServerInterfaceWrapper) CreateInvoice(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateInvoice(c)
}

// DeleteInvoice operation middleware
func (siw *ServerInterfaceWrapper) DeleteInvoice(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteInvoice(c, id)
}

// GetInvoice operation middleware
func (siw *ServerInterfaceWrapper) GetInvoice(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInvoice(c, id)
}

// UpdateInvoice operation middleware
func (siw *ServerInterfaceWrapper) UpdateInvoice(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateInvoice(c, id)
}

// MerchantProfile operation middleware
func (siw *ServerInterfaceWrapper) MerchantProfile(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MerchantProfile(c)
}

// ListRefundHistory operation middleware
func (siw *ServerInterfaceWrapper) ListRefundHistory(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRefundHistoryParams

	// ------------- Optional query parameter "merchantId" -------------

	err = runtime.BindQueryParameter("form", true, false, "merchantId", c.Request.URL.Query(), &params.MerchantId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter merchantId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRefundHistory(c, params)
}

// RequestRefund operation middleware
func (siw *ServerInterfaceWrapper) RequestRefund(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestRefund(c)
}

// ListTopUpHistory operation middleware
func (siw *ServerInterfaceWrapper) ListTopUpHistory(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTopUpHistoryParams

	// ------------- Optional query parameter "merchantId" -------------

	err = runtime.BindQueryParameter("form", true, false, "merchantId", c.Request.URL.Query(), &params.MerchantId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter merchantId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTopUpHistory(c, params)
}

// RequestTopUp operation middleware
func (siw *ServerInterfaceWrapper) RequestTopUp(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestTopUp(c)
}

// ResolvePaymentLink operation middleware
func (siw *ServerInterfaceWrapper) ResolvePaymentLink(c *gin.Context) {

	var err error

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", c.Param("token"), &token, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResolvePaymentLink(c, token)
}

// CreatePaymentIntent operation middleware
func (siw *ServerInterfaceWrapper) CreatePaymentIntent(c *gin.Context) {

	var err error

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", c.Param("token"), &token, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePaymentIntent(c, token)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin/dashboard", wrapper.AdminDashboard)
	router.GET(options.BaseURL+"/admin/dashboard/stats", wrapper.GetDashboardStats)
	router.POST(options.BaseURL+"/admin/payment-intents/:intentId/simulate", wrapper.SimulatePaymentIntent)
	router.POST(options.BaseURL+"/admin/refunds/:refundId/approve", wrapper.ApproveRefund)
	router.POST(options.BaseURL+"/admin/refunds/:refundId/process", wrapper.ProcessRefund)
	router.POST(options.BaseURL+"/admin/refunds/:refundId/reject", wrapper.RejectRefund)
	router.POST(options.BaseURL+"/admin/topups/:topupId/status", wrapper.UpdateTopUpStatus)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.GET(options.BaseURL+"/health", wrapper.Health)
	router.GET(options.BaseURL+"/invoices", wrapper.ListInvoices)
	router.POST(options.BaseURL+"/invoices", wrapper.CreateInvoice)
	router.DELETE(options.BaseURL+"/invoices/:id", wrapper.DeleteInvoice)
	router.GET(options.BaseURL+"/invoices/:id", wrapper.GetInvoice)
	router.PUT(options.BaseURL+"/invoices/:id", wrapper.UpdateInvoice)
	router.GET(options.BaseURL+"/merchant/profile", wrapper.MerchantProfile)
	router.GET(options.BaseURL+"/merchant/refunds", wrapper.ListRefundHistory)
	router.POST(options.BaseURL+"/merchant/refunds", wrapper.RequestRefund)
	router.GET(options.BaseURL+"/merchant/topups", wrapper.ListTopUpHistory)
	router.POST(options.BaseURL+"/merchant/topups", wrapper.RequestTopUp)
	router.GET(options.BaseURL+"/pay/:token", wrapper.ResolvePaymentLink)
	router.POST(options.BaseURL+"/pay/:token/intents", wrapper.CreatePaymentIntent)
}

type AdminDashboardRequestObject struct {
}

type AdminDashboardResponseObject interface {
	VisitAdminDashboardResponse(w http.ResponseWriter) error
}

type AdminDashboard200Response struct {
}

func (response AdminDashboard200Response) VisitAdminDashboardResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetDashboardStatsRequestObject struct {
	Params GetDashboardStatsParams
}

type GetDashboardStatsResponseObject interface {
	VisitGetDashboardStatsResponse(w http.ResponseWriter) error
}

type GetDashboardStats200Response struct {
}

func (response GetDashboardStats200Response) VisitGetDashboardStatsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetDashboardStats400JSONResponse ErrorResponse

func (response GetDashboardStats400JSONResponse) VisitGetDashboardStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SimulatePaymentIntentRequestObject struct {
	IntentId string `json:"intentId"`
	Body     *SimulatePaymentIntentJSONRequestBody
}

type SimulatePaymentIntentResponseObject interface {
	VisitSimulatePaymentIntentResponse(w http.ResponseWriter) error
}

type SimulatePaymentIntent200Response struct {
}

func (response SimulatePaymentIntent200Response) VisitSimulatePaymentIntentResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SimulatePaymentIntent400JSONResponse ErrorResponse

func (response SimulatePaymentIntent400JSONResponse) VisitSimulatePaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApproveRefundRequestObject struct {
	RefundId string `json:"refundId"`
}

type ApproveRefundResponseObject interface {
	VisitApproveRefundResponse(w http.ResponseWriter) error
}

type ApproveRefund200Response struct {
}

func (response ApproveRefund200Response) VisitApproveRefundResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ApproveRefund400JSONResponse ErrorResponse

func (response ApproveRefund400JSONResponse) VisitApproveRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ProcessRefundRequestObject struct {
	RefundId string `json:"refundId"`
	Body     *ProcessRefundJSONRequestBody
}

type ProcessRefundResponseObject interface {
	VisitProcessRefundResponse(w http.ResponseWriter) error
}

type ProcessRefund200Response struct {
}

func (response ProcessRefund200Response) VisitProcessRefundResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ProcessRefund400JSONResponse ErrorResponse

func (response ProcessRefund400JSONResponse) VisitProcessRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RejectRefundRequestObject struct {
	RefundId string `json:"refundId"`
}

type RejectRefundResponseObject interface {
	VisitRejectRefundResponse(w http.ResponseWriter) error
}

type RejectRefund200Response struct {
}

func (response RejectRefund200Response) VisitRejectRefundResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RejectRefund400JSONResponse ErrorResponse

func (response RejectRefund400JSONResponse) VisitRejectRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTopUpStatusRequestObject struct {
	TopupId string `json:"topupId"`
	Body    *UpdateTopUpStatusJSONRequestBody
}

type UpdateTopUpStatusResponseObject interface {
	VisitUpdateTopUpStatusResponse(w http.ResponseWriter) error
}

type UpdateTopUpStatus200Response struct {
}

func (response UpdateTopUpStatus200Response) VisitUpdateTopUpStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateTopUpStatus400JSONResponse ErrorResponse

func (response UpdateTopUpStatus400JSONResponse) VisitUpdateTopUpStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse ErrorResponse

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login409JSONResponse ErrorResponse

func (response Login409JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse ErrorResponse

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RefreshRequestObject struct {
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200JSONResponse AuthResponse

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Refresh401JSONResponse ErrorResponse

func (response Refresh401JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Register400JSONResponse ErrorResponse

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Register401JSONResponse ErrorResponse

func (response Register401JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type Register500JSONResponse ErrorResponse

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200Response struct {
}

func (response Health200Response) VisitHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ListInvoicesRequestObject struct {
	Params ListInvoicesParams
}

type ListInvoicesResponseObject interface {
	VisitListInvoicesResponse(w http.ResponseWriter) error
}

type ListInvoices200JSONResponse InvoiceListResponse

func (response ListInvoices200JSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListInvoices500JSONResponse ErrorResponse

func (response ListInvoices500JSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvoiceRequestObject struct {
	Body *CreateInvoiceJSONRequestBody
}

type CreateInvoiceResponseObject interface {
	VisitCreateInvoiceResponse(w http.ResponseWriter) error
}

type CreateInvoice201JSONResponse InvoiceResponse

func (response CreateInvoice201JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvoice400JSONResponse ErrorResponse

func (response CreateInvoice400JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvoice500JSONResponse ErrorResponse

func (response CreateInvoice500JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteInvoiceRequestObject struct {
	Id string `json:"id"`
}

type DeleteInvoiceResponseObject interface {
	VisitDeleteInvoiceResponse(w http.ResponseWriter) error
}

type DeleteInvoice204Response struct {
}

func (response DeleteInvoice204Response) VisitDeleteInvoiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteInvoice400JSONResponse ErrorResponse

func (response DeleteInvoice400JSONResponse) VisitDeleteInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteInvoice404JSONResponse ErrorResponse

func (response DeleteInvoice404JSONResponse) VisitDeleteInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetInvoiceRequestObject struct {
	Id string `json:"id"`
}

type GetInvoiceResponseObject interface {
	VisitGetInvoiceResponse(w http.ResponseWriter) error
}

type GetInvoice200JSONResponse InvoiceResponse

func (response GetInvoice200JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInvoice404JSONResponse ErrorResponse

func (response GetInvoice404JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateInvoiceRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateInvoiceJSONRequestBody
}

type UpdateInvoiceResponseObject interface {
	VisitUpdateInvoiceResponse(w http.ResponseWriter) error
}

type UpdateInvoice200JSONResponse InvoiceResponse

func (response UpdateInvoice200JSONResponse) VisitUpdateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateInvoice400JSONResponse ErrorResponse

func (response UpdateInvoice400JSONResponse) VisitUpdateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateInvoice404JSONResponse ErrorResponse

func (response UpdateInvoice404JSONResponse) VisitUpdateInvoiceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MerchantProfileRequestObject struct {
}

type MerchantProfileResponseObject interface {
	VisitMerchantProfileResponse(w http.ResponseWriter) error
}

type MerchantProfile200Response struct {
}

func (response MerchantProfile200Response) VisitMerchantProfileResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ListRefundHistoryRequestObject struct {
	Params ListRefundHistoryParams
}

type ListRefundHistoryResponseObject interface {
	VisitListRefundHistoryResponse(w http.ResponseWriter) error
}

type ListRefundHistory200Response struct {
}

func (response ListRefundHistory200Response) VisitListRefundHistoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RequestRefundRequestObject struct {
	Body *RequestRefundJSONRequestBody
}

type RequestRefundResponseObject interface {
	VisitRequestRefundResponse(w http.ResponseWriter) error
}

type RequestRefund201Response struct {
}

func (response RequestRefund201Response) VisitRequestRefundResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type RequestRefund400JSONResponse ErrorResponse

func (response RequestRefund400JSONResponse) VisitRequestRefundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListTopUpHistoryRequestObject struct {
	Params ListTopUpHistoryParams
}

type ListTopUpHistoryResponseObject interface {
	VisitListTopUpHistoryResponse(w http.ResponseWriter) error
}

type ListTopUpHistory200Response struct {
}

func (response ListTopUpHistory200Response) VisitListTopUpHistoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RequestTopUpRequestObject struct {
	Body *RequestTopUpJSONRequestBody
}

type RequestTopUpResponseObject interface {
	VisitRequestTopUpResponse(w http.ResponseWriter) error
}

type RequestTopUp201Response struct {
}

func (response RequestTopUp201Response) VisitRequestTopUpResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type RequestTopUp400JSONResponse ErrorResponse

func (response RequestTopUp400JSONResponse) VisitRequestTopUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ResolvePaymentLinkRequestObject struct {
	Token string `json:"token"`
}

type ResolvePaymentLinkResponseObject interface {
	VisitResolvePaymentLinkResponse(w http.ResponseWriter) error
}

type ResolvePaymentLink200Response struct {
}

func (response ResolvePaymentLink200Response) VisitResolvePaymentLinkResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ResolvePaymentLink404JSONResponse ErrorResponse

func (response ResolvePaymentLink404JSONResponse) VisitResolvePaymentLinkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreatePaymentIntentRequestObject struct {
	Token string `json:"token"`
	Body  *CreatePaymentIntentJSONRequestBody
}

type CreatePaymentIntentResponseObject interface {
	VisitCreatePaymentIntentResponse(w http.ResponseWriter) error
}

type CreatePaymentIntent201Response struct {
}

func (response CreatePaymentIntent201Response) VisitCreatePaymentIntentResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreatePaymentIntent400JSONResponse ErrorResponse

func (response CreatePaymentIntent400JSONResponse) VisitCreatePaymentIntentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Admin-only dashboard/access check
	// (GET /admin/dashboard)
	AdminDashboard(ctx context.Context, request AdminDashboardRequestObject) (AdminDashboardResponseObject, error)
	// Admin dashboard statistics
	// (GET /admin/dashboard/stats)
	GetDashboardStats(ctx context.Context, request GetDashboardStatsRequestObject) (GetDashboardStatsResponseObject, error)
	// Admin simulate payment intent outcome
	// (POST /admin/payment-intents/{intentId}/simulate)
	SimulatePaymentIntent(ctx context.Context, request SimulatePaymentIntentRequestObject) (SimulatePaymentIntentResponseObject, error)
	// Admin approve refund
	// (POST /admin/refunds/{refundId}/approve)
	ApproveRefund(ctx context.Context, request ApproveRefundRequestObject) (ApproveRefundResponseObject, error)
	// Admin process refund outcome
	// (POST /admin/refunds/{refundId}/process)
	ProcessRefund(ctx context.Context, request ProcessRefundRequestObject) (ProcessRefundResponseObject, error)
	// Admin reject refund
	// (POST /admin/refunds/{refundId}/reject)
	RejectRefund(ctx context.Context, request RejectRefundRequestObject) (RejectRefundResponseObject, error)
	// Admin update top-up status
	// (POST /admin/topups/{topupId}/status)
	UpdateTopUpStatus(ctx context.Context, request UpdateTopUpStatusRequestObject) (UpdateTopUpStatusResponseObject, error)
	// Login merchant account
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Refresh JWT token
	// (POST /auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Register an account
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Health check
	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
	// List invoices
	// (GET /invoices)
	ListInvoices(ctx context.Context, request ListInvoicesRequestObject) (ListInvoicesResponseObject, error)
	// Create invoice
	// (POST /invoices)
	CreateInvoice(ctx context.Context, request CreateInvoiceRequestObject) (CreateInvoiceResponseObject, error)
	// Delete invoice
	// (DELETE /invoices/{id})
	DeleteInvoice(ctx context.Context, request DeleteInvoiceRequestObject) (DeleteInvoiceResponseObject, error)
	// Get invoice detail
	// (GET /invoices/{id})
	GetInvoice(ctx context.Context, request GetInvoiceRequestObject) (GetInvoiceResponseObject, error)
	// Update invoice
	// (PUT /invoices/{id})
	UpdateInvoice(ctx context.Context, request UpdateInvoiceRequestObject) (UpdateInvoiceResponseObject, error)
	// Merchant-only profile/access check
	// (GET /merchant/profile)
	MerchantProfile(ctx context.Context, request MerchantProfileRequestObject) (MerchantProfileResponseObject, error)
	// Refund history
	// (GET /merchant/refunds)
	ListRefundHistory(ctx context.Context, request ListRefundHistoryRequestObject) (ListRefundHistoryResponseObject, error)
	// Merchant request refund
	// (POST /merchant/refunds)
	RequestRefund(ctx context.Context, request RequestRefundRequestObject) (RequestRefundResponseObject, error)
	// Top-up history
	// (GET /merchant/topups)
	ListTopUpHistory(ctx context.Context, request ListTopUpHistoryRequestObject) (ListTopUpHistoryResponseObject, error)
	// Merchant request top-up
	// (POST /merchant/topups)
	RequestTopUp(ctx context.Context, request RequestTopUpRequestObject) (RequestTopUpResponseObject, error)
	// Resolve public payment link
	// (GET /pay/{token})
	ResolvePaymentLink(ctx context.Context, request ResolvePaymentLinkRequestObject) (ResolvePaymentLinkResponseObject, error)
	// Create payment intent
	// (POST /pay/{token}/intents)
	CreatePaymentIntent(ctx context.Context, request CreatePaymentIntentRequestObject) (CreatePaymentIntentResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AdminDashboard operation middleware
func (sh *strictHandler) AdminDashboard(ctx *gin.Context) {
	var request AdminDashboardRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminDashboard(ctx, request.(AdminDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminDashboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(AdminDashboardResponseObject); ok {
		if err := validResponse.VisitAdminDashboardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDashboardStats operation middleware
func (sh *strictHandler) GetDashboardStats(ctx *gin.Context, params GetDashboardStatsParams) {
	var request GetDashboardStatsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDashboardStats(ctx, request.(GetDashboardStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDashboardStats")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetDashboardStatsResponseObject); ok {
		if err := validResponse.VisitGetDashboardStatsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SimulatePaymentIntent operation middleware
func (sh *strictHandler) SimulatePaymentIntent(ctx *gin.Context, intentId string) {
	var request SimulatePaymentIntentRequestObject

	request.IntentId = intentId

	var body SimulatePaymentIntentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SimulatePaymentIntent(ctx, request.(SimulatePaymentIntentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimulatePaymentIntent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SimulatePaymentIntentResponseObject); ok {
		if err := validResponse.VisitSimulatePaymentIntentResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApproveRefund operation middleware
func (sh *strictHandler) ApproveRefund(ctx *gin.Context, refundId string) {
	var request ApproveRefundRequestObject

	request.RefundId = refundId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveRefund(ctx, request.(ApproveRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveRefund")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ApproveRefundResponseObject); ok {
		if err := validResponse.VisitApproveRefundResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProcessRefund operation middleware
func (sh *strictHandler) ProcessRefund(ctx *gin.Context, refundId string) {
	var request ProcessRefundRequestObject

	request.RefundId = refundId

	var body ProcessRefundJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProcessRefund(ctx, request.(ProcessRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProcessRefund")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ProcessRefundResponseObject); ok {
		if err := validResponse.VisitProcessRefundResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RejectRefund operation middleware
func (sh *strictHandler) RejectRefund(ctx *gin.Context, refundId string) {
	var request RejectRefundRequestObject

	request.RefundId = refundId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RejectRefund(ctx, request.(RejectRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RejectRefund")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RejectRefundResponseObject); ok {
		if err := validResponse.VisitRejectRefundResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTopUpStatus operation middleware
func (sh *strictHandler) UpdateTopUpStatus(ctx *gin.Context, topupId string) {
	var request UpdateTopUpStatusRequestObject

	request.TopupId = topupId

	var body UpdateTopUpStatusJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTopUpStatus(ctx, request.(UpdateTopUpStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTopUpStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateTopUpStatusResponseObject); ok {
		if err := validResponse.VisitUpdateTopUpStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(ctx *gin.Context) {
	var request RefreshRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(ctx *gin.Context) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *gin.Context) {
	var request HealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInvoices operation middleware
func (sh *strictHandler) ListInvoices(ctx *gin.Context, params ListInvoicesParams) {
	var request ListInvoicesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvoices(ctx, request.(ListInvoicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvoices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListInvoicesResponseObject); ok {
		if err := validResponse.VisitListInvoicesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInvoice operation middleware
func (sh *strictHandler) CreateInvoice(ctx *gin.Context) {
	var request CreateInvoiceRequestObject

	var body CreateInvoiceJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvoice(ctx, request.(CreateInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateInvoiceResponseObject); ok {
		if err := validResponse.VisitCreateInvoiceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteInvoice operation middleware
func (sh *strictHandler) DeleteInvoice(ctx *gin.Context, id string) {
	var request DeleteInvoiceRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInvoice(ctx, request.(DeleteInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteInvoiceResponseObject); ok {
		if err := validResponse.VisitDeleteInvoiceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInvoice operation middleware
func (sh *strictHandler) GetInvoice(ctx *gin.Context, id string) {
	var request GetInvoiceRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInvoice(ctx, request.(GetInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetInvoiceResponseObject); ok {
		if err := validResponse.VisitGetInvoiceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateInvoice operation middleware
func (sh *strictHandler) UpdateInvoice(ctx *gin.Context, id string) {
	var request UpdateInvoiceRequestObject

	request.Id = id

	var body UpdateInvoiceJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateInvoice(ctx, request.(UpdateInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateInvoiceResponseObject); ok {
		if err := validResponse.VisitUpdateInvoiceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// MerchantProfile operation middleware
func (sh *strictHandler) MerchantProfile(ctx *gin.Context) {
	var request MerchantProfileRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MerchantProfile(ctx, request.(MerchantProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MerchantProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(MerchantProfileResponseObject); ok {
		if err := validResponse.VisitMerchantProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRefundHistory operation middleware
func (sh *strictHandler) ListRefundHistory(ctx *gin.Context, params ListRefundHistoryParams) {
	var request ListRefundHistoryRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRefundHistory(ctx, request.(ListRefundHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRefundHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListRefundHistoryResponseObject); ok {
		if err := validResponse.VisitListRefundHistoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestRefund operation middleware
func (sh *strictHandler) RequestRefund(ctx *gin.Context) {
	var request RequestRefundRequestObject

	var body RequestRefundJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestRefund(ctx, request.(RequestRefundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestRefund")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RequestRefundResponseObject); ok {
		if err := validResponse.VisitRequestRefundResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTopUpHistory operation middleware
func (sh *strictHandler) ListTopUpHistory(ctx *gin.Context, params ListTopUpHistoryParams) {
	var request ListTopUpHistoryRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTopUpHistory(ctx, request.(ListTopUpHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTopUpHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListTopUpHistoryResponseObject); ok {
		if err := validResponse.VisitListTopUpHistoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestTopUp operation middleware
func (sh *strictHandler) RequestTopUp(ctx *gin.Context) {
	var request RequestTopUpRequestObject

	var body RequestTopUpJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestTopUp(ctx, request.(RequestTopUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestTopUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RequestTopUpResponseObject); ok {
		if err := validResponse.VisitRequestTopUpResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResolvePaymentLink operation middleware
func (sh *strictHandler) ResolvePaymentLink(ctx *gin.Context, token string) {
	var request ResolvePaymentLinkRequestObject

	request.Token = token

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ResolvePaymentLink(ctx, request.(ResolvePaymentLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolvePaymentLink")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ResolvePaymentLinkResponseObject); ok {
		if err := validResponse.VisitResolvePaymentLinkResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePaymentIntent operation middleware
func (sh *strictHandler) CreatePaymentIntent(ctx *gin.Context, token string) {
	var request CreatePaymentIntentRequestObject

	request.Token = token

	var body CreatePaymentIntentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePaymentIntent(ctx, request.(CreatePaymentIntentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePaymentIntent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreatePaymentIntentResponseObject); ok {
		if err := validResponse.VisitCreatePaymentIntentResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
