// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/gonszalito/go-ddd-architecture/internal/application/dashboard"
	"github.com/gonszalito/go-ddd-architecture/internal/application/invoice"
	"github.com/gonszalito/go-ddd-architecture/internal/application/payment"
	"github.com/gonszalito/go-ddd-architecture/internal/application/refund"
	"github.com/gonszalito/go-ddd-architecture/internal/application/topup"
	"github.com/gonszalito/go-ddd-architecture/internal/application/user"
	"github.com/gonszalito/go-ddd-architecture/internal/application/wallet"
	"github.com/gonszalito/go-ddd-architecture/internal/config"
	"github.com/gonszalito/go-ddd-architecture/internal/infrastructure/database"
	"log"
	"time"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeUserService is the Wire injector that constructs the UserService and cleanup.
func InitializeUserService() (*user.UserService, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	userRepository, err := ProvideUserRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := ProvideUserService(config, userRepository)
	return userService, func() {
		cleanup()
	}, nil
}

func InitializeApp() (*App, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDatabase(config)
	if err != nil {
		return nil, nil, err
	}
	userRepository, err := ProvideUserRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := ProvideUserService(config, userRepository)
	invoiceRepository, err := ProvideInvoiceRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	service := ProvideInvoiceService(invoiceRepository)
	repository, err := ProvidePaymentRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	paymentService := ProvidePaymentService(repository, service)
	refundRepository, err := ProvideRefundRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	walletRepository, err := ProvideWalletRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	refundService := ProvideRefundService(refundRepository, walletRepository, service)
	topupRepository, err := ProvideTopUpRepository(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	topupService := ProvideTopUpService(topupRepository, walletRepository)
	dashboardService := ProvideDashboardService(invoiceRepository, repository, refundRepository)
	app := ProvideApp(userService, service, paymentService, refundService, topupService, dashboardService)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// ProvideConfig loads application configuration from environment.
func ProvideConfig() (*config.Config, error) {
	return config.Load()
}

type App struct {
	UserService    *user.UserService
	InvoiceService *invoice.Service
	PaymentService *payment.Service
	RefundService  *refund.Service
	TopUpService   *topup.Service
	Dashboard      *dashboard.Service
}

func ProvideDatabase(cfg *config.Config) (*sql.DB, func(), error) {
	dsn := cfg.DatabaseURL
	if dsn == "" {
		dsn = fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable", cfg.DBUser, cfg.DBPassword, cfg.DBHost, cfg.DBPort, cfg.DBName)
	}

	db, err := sql.Open("postgres", dsn)
	if err != nil {
		return nil, func() {}, err
	}

	if err := pingDB(db); err != nil {
		_ = db.Close()
		return nil, func() {}, err
	}

	cleanup := func() {
		if err := db.Close(); err != nil {
			log.Println("error closing DB:", err)
		}
	}
	return db, cleanup, nil
}

func ProvideUserRepository(db *sql.DB) (user.UserRepository, error) {
	return database.NewPostgresUserRepository(db), nil
}

func pingDB(db *sql.DB) error {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	return db.PingContext(ctx)
}

// ProvideUserService wires the application service.
func ProvideUserService(cfg *config.Config, repo user.UserRepository) *user.UserService {
	return user.NewUserService(repo, cfg.JWTSecret, cfg.JWTExpiryMinutes)
}

func ProvideInvoiceRepository(db *sql.DB) (invoice.InvoiceRepository, error) {
	return database.NewPostgresInvoiceRepository(db), nil
}

func ProvideInvoiceService(repo invoice.InvoiceRepository) *invoice.Service {
	return invoice.NewService(repo)
}

func ProvidePaymentRepository(db *sql.DB) (payment.Repository, error) {
	return database.NewPostgresPaymentRepository(db), nil
}

func ProvideRefundRepository(db *sql.DB) (refund.Repository, error) {
	return database.NewPostgresRefundRepository(db), nil
}

func ProvideTopUpRepository(db *sql.DB) (topup.Repository, error) {
	return database.NewPostgresTopUpRepository(db), nil
}

func ProvideWalletRepository(db *sql.DB) (wallet.Repository, error) {
	return database.NewPostgresWalletRepository(db), nil
}

func ProvidePaymentService(repo payment.Repository, invoiceService *invoice.Service) *payment.Service {
	return payment.NewService(repo, invoiceService)
}

func ProvideRefundService(repo refund.Repository, walletRepo wallet.Repository, invoiceService *invoice.Service) *refund.Service {
	return refund.NewService(repo, walletRepo, invoiceService)
}

func ProvideTopUpService(repo topup.Repository, walletRepo wallet.Repository) *topup.Service {
	return topup.NewService(repo, walletRepo)
}

func ProvideDashboardService(invoiceRepo invoice.InvoiceRepository, paymentRepo payment.Repository, refundRepo refund.Repository) *dashboard.Service {
	return dashboard.NewService(invoiceRepo, paymentRepo, refundRepo)
}

func ProvideApp(
	userService *user.UserService,
	invoiceService *invoice.Service,
	paymentService *payment.Service,
	refundService *refund.Service,
	topupService *topup.Service,
	dashboardService *dashboard.Service,
) *App {
	return &App{
		UserService:    userService,
		InvoiceService: invoiceService,
		PaymentService: paymentService,
		RefundService:  refundService,
		TopUpService:   topupService,
		Dashboard:      dashboardService,
	}
}
